name: array2d
version: 1.5.0
homepage: https://github.com/s1r1m1r1/array2d
environment:
  sdk: ^3.5.0
description: Array2d
dependencies:
  test: ^1.26.2
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
resolution: workspace
